[project]
name = "rpa-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.127.0",
    "playwright>=1.57.0",
    "requests>=2.32.5",
    "urllib3>=2.6.2",
    "uvicorn[standard]>=0.40.0",
]
